package com.niucong.scsystem.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DrugInfo.
 */
public class DrugInfo {

    private long BarCode;
    /** Not-null value. */
    private String Name;
    private String Factory;
    /** Not-null value. */
    private String NamePY;
    /** Not-null value. */
    private String NamePYF;

    public DrugInfo() {
    }

    public DrugInfo(long BarCode) {
        this.BarCode = BarCode;
    }

    public DrugInfo(long BarCode, String Name, String Factory, String NamePY, String NamePYF) {
        this.BarCode = BarCode;
        this.Name = Name;
        this.Factory = Factory;
        this.NamePY = NamePY;
        this.NamePYF = NamePYF;
    }

    public long getBarCode() {
        return BarCode;
    }

    public void setBarCode(long BarCode) {
        this.BarCode = BarCode;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getFactory() {
        return Factory;
    }

    public void setFactory(String Factory) {
        this.Factory = Factory;
    }

    /** Not-null value. */
    public String getNamePY() {
        return NamePY;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNamePY(String NamePY) {
        this.NamePY = NamePY;
    }

    /** Not-null value. */
    public String getNamePYF() {
        return NamePYF;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNamePYF(String NamePYF) {
        this.NamePYF = NamePYF;
    }

}
