package com.niucong.scsystem.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table StoreList.
 */
public class StoreList {

    private long BarCode;
    private Integer Number;
    private Integer Price;
    private Integer WarnNumber;

    public StoreList() {
    }

    public StoreList(long BarCode) {
        this.BarCode = BarCode;
    }

    public StoreList(long BarCode, Integer Number, Integer Price, Integer WarnNumber) {
        this.BarCode = BarCode;
        this.Number = Number;
        this.Price = Price;
        this.WarnNumber = WarnNumber;
    }

    public long getBarCode() {
        return BarCode;
    }

    public void setBarCode(long BarCode) {
        this.BarCode = BarCode;
    }

    public Integer getNumber() {
        return Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

    public Integer getPrice() {
        return Price;
    }

    public void setPrice(Integer Price) {
        this.Price = Price;
    }

    public Integer getWarnNumber() {
        return WarnNumber;
    }

    public void setWarnNumber(Integer WarnNumber) {
        this.WarnNumber = WarnNumber;
    }

}
