package com.niucong.scsystem.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DrugInfo.
 */
public class DrugInfo {

    private long BarCode;
    /** Not-null value. */
    private String Name;
    private String Factory;

    public DrugInfo() {
    }

    public DrugInfo(long BarCode) {
        this.BarCode = BarCode;
    }

    public DrugInfo(long BarCode, String Name, String Factory) {
        this.BarCode = BarCode;
        this.Name = Name;
        this.Factory = Factory;
    }

    public long getBarCode() {
        return BarCode;
    }

    public void setBarCode(long BarCode) {
        this.BarCode = BarCode;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getFactory() {
        return Factory;
    }

    public void setFactory(String Factory) {
        this.Factory = Factory;
    }

}
