package com.niucong.scsystem.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EnterRecord.
 */
public class EnterRecord {

    private Long id;
    private long BarCode;
    private Integer Number;
    private Integer Price;
    /** Not-null value. */
    private java.util.Date EnterDate;

    public EnterRecord() {
    }

    public EnterRecord(Long id) {
        this.id = id;
    }

    public EnterRecord(Long id, long BarCode, Integer Number, Integer Price, java.util.Date EnterDate) {
        this.id = id;
        this.BarCode = BarCode;
        this.Number = Number;
        this.Price = Price;
        this.EnterDate = EnterDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBarCode() {
        return BarCode;
    }

    public void setBarCode(long BarCode) {
        this.BarCode = BarCode;
    }

    public Integer getNumber() {
        return Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

    public Integer getPrice() {
        return Price;
    }

    public void setPrice(Integer Price) {
        this.Price = Price;
    }

    /** Not-null value. */
    public java.util.Date getEnterDate() {
        return EnterDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnterDate(java.util.Date EnterDate) {
        this.EnterDate = EnterDate;
    }

}
