package com.niucong.scsystem.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.io.Serializable;

/**
 * Entity mapped to table SellRecord.
 */
public class SellRecord implements Serializable {

    private Long id;
    private long BarCode;
    private Integer Number;
    private Integer Price;
    private Integer PayType;
    /** Not-null value. */
    private java.util.Date SellDate;

    public SellRecord() {
    }

    public SellRecord(Long id) {
        this.id = id;
    }

    public SellRecord(Long id, long BarCode, Integer Number, Integer Price, Integer PayType, java.util.Date SellDate) {
        this.id = id;
        this.BarCode = BarCode;
        this.Number = Number;
        this.Price = Price;
        this.PayType = PayType;
        this.SellDate = SellDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBarCode() {
        return BarCode;
    }

    public void setBarCode(long BarCode) {
        this.BarCode = BarCode;
    }

    public Integer getNumber() {
        return Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

    public Integer getPrice() {
        return Price;
    }

    public void setPrice(Integer Price) {
        this.Price = Price;
    }

    public Integer getPayType() {
        return PayType;
    }

    public void setPayType(Integer PayType) {
        this.PayType = PayType;
    }

    /** Not-null value. */
    public java.util.Date getSellDate() {
        return SellDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSellDate(java.util.Date SellDate) {
        this.SellDate = SellDate;
    }

}
